CREATE DATABASE IF NOT EXISTS petclinic;

CREATE USER IF NOT EXISTS 'pc'@'localhost' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'localhost';

CREATE TABLE IF NOT EXISTS invoices (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(10,2) NOT NULL,
  due_date DATE,
  status VARCHAR(32) DEFAULT 'OPEN',
  visit_id INT(4) UNSIGNED NOT NULL
) ENGINE=InnoDB;