CREATE DATABASE IF NOT EXISTS petclinic;

CREATE USER IF NOT EXISTS 'pc'@'localhost' IDENTIFIED BY 'pc';
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'localhost';

CREATE TABLE IF NOT EXISTS visits (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pet_id INT(4) UNSIGNED NOT NULL,
  visit_date DATE,
  description VARCHAR(8192)
) engine=InnoDB;
